# Generated by Django 5.2.11 on 2026-02-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bailleur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255, verbose_name="Nom complet")),
                (
                    "sigle",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Sigle / Acronyme"
                    ),
                ),
                (
                    "type_bailleur",
                    models.CharField(
                        choices=[
                            ("multilateral", "Multilatéral"),
                            ("bilateral", "Bilatéral"),
                            ("regional", "Régional"),
                            ("prive", "Privé"),
                            ("ong", "ONG Internationale"),
                            ("autre", "Autre"),
                        ],
                        default="multilateral",
                        max_length=20,
                        verbose_name="Type de bailleur",
                    ),
                ),
                (
                    "pays_siege",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Pays du siège"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("site_web", models.URLField(blank=True, verbose_name="Site web")),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email de contact"
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bailleur",
                "verbose_name_plural": "Bailleurs",
                "ordering": ["nom"],
            },
        ),
    ]
