# Generated by Django 5.2.11 on 2026-02-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bailleurs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bailleur",
            name="categorie_institutionnelle",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bretton_woods", "Institutions de Bretton Woods"),
                    ("systeme_nu", "Système des Nations Unies"),
                    ("banque_multilaterale", "Banques multilatérales de développement"),
                    ("cooperation_bilaterale", "Coopération bilatérale"),
                    ("institution_regionale", "Institutions régionales africaines"),
                    ("fonds_vertical", "Fonds verticaux / thématiques"),
                    ("secteur_prive", "Secteur privé / Fondations"),
                    ("ong_internationale", "ONG internationales"),
                    ("autre", "Autre"),
                ],
                default="autre",
                max_length=30,
                verbose_name="Catégorie institutionnelle",
            ),
        ),
    ]
