# Generated by Django 5.2.11 on 2026-05-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bailleurs", "0002_bailleur_categorie_institutionnelle"),
    ]

    operations = [
        migrations.AddField(
            model_name="bailleur",
            name="contact_telephone",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Téléphone de contact"
            ),
        ),
        migrations.AddField(
            model_name="bailleur",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="logos_bailleurs/", verbose_name="Logo"
            ),
        ),
        migrations.AddField(
            model_name="bailleur",
            name="seuil_significativite",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Montant minimal en dessous duquel l'intervention est négligeable (0 = pas de seuil)",
                max_digits=15,
                verbose_name="Seuil de significativité",
            ),
        ),
    ]
