# Generated by Django 5.2.11 on 2026-05-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bailleurs", "0003_bailleur_contact_telephone_bailleur_logo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bailleur",
            name="contact_telephone",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Téléphone du contact CI"
            ),
        ),
        migrations.AlterField(
            model_name="bailleur",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="bailleurs/logos/",
                verbose_name="Logo (PNG/SVG)",
            ),
        ),
        migrations.AlterField(
            model_name="bailleur",
            name="seuil_significativite",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Montant minimal en FCFA en dessous duquel le bailleur est considéré comme négligeable",
                max_digits=15,
                verbose_name="Seuil de significativité (FCFA)",
            ),
        ),
    ]
