# Generated by Django 5.2.11 on 2026-02-24 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bailleurs", "0001_initial"),
        ("projets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Financement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_financement",
                    models.CharField(
                        choices=[
                            ("don", "Don"),
                            ("pret_concessionnel", "Prêt concessionnel"),
                            ("pret_non_concessionnel", "Prêt non concessionnel"),
                            ("assistance_technique", "Assistance technique"),
                            ("cofinancement", "Cofinancement"),
                            ("contrepartie", "Contrepartie nationale"),
                            ("autre", "Autre"),
                        ],
                        default="don",
                        max_length=30,
                        verbose_name="Type de financement",
                    ),
                ),
                (
                    "montant_engage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Montant engagé",
                    ),
                ),
                (
                    "devise",
                    models.CharField(
                        choices=[
                            ("USD", "Dollar US (USD)"),
                            ("EUR", "Euro (EUR)"),
                            ("XOF", "Franc CFA (XOF)"),
                            ("GBP", "Livre Sterling (GBP)"),
                            ("JPY", "Yen Japonais (JPY)"),
                            ("CHF", "Franc Suisse (CHF)"),
                        ],
                        default="USD",
                        max_length=3,
                        verbose_name="Devise",
                    ),
                ),
                (
                    "date_accord",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'accord"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence accord"
                    ),
                ),
                (
                    "observations",
                    models.TextField(blank=True, verbose_name="Observations"),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "bailleur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financements",
                        to="bailleurs.bailleur",
                        verbose_name="Bailleur",
                    ),
                ),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financements",
                        to="projets.projet",
                        verbose_name="Projet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financement",
                "verbose_name_plural": "Financements",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="Decaissement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Montant décaissé"
                    ),
                ),
                (
                    "date_decaissement",
                    models.DateField(verbose_name="Date de décaissement"),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "financement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decaissements",
                        to="financements.financement",
                        verbose_name="Financement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Décaissement",
                "verbose_name_plural": "Décaissements",
                "ordering": ["-date_decaissement"],
            },
        ),
    ]
