# Generated by Django 5.2.11 on 2026-05-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="decaissement",
            name="date_previsionnel",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Date prévisionnelle de décaissement",
            ),
        ),
        migrations.AddField(
            model_name="financement",
            name="est_appui_budgetaire",
            field=models.BooleanField(
                default=False,
                help_text="Cocher si ce financement constitue un appui budgétaire direct",
                verbose_name="Appui budgétaire",
            ),
        ),
        migrations.AddField(
            model_name="financement",
            name="taux_conversion_contractuel",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Taux FCFA fixé à la date de signature (ne change pas)",
                max_digits=12,
                null=True,
                verbose_name="Taux de conversion contractuel",
            ),
        ),
    ]
