# Generated by Django 5.2.11 on 2026-05-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financements", "0002_decaissement_date_previsionnel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="decaissement",
            name="date_previsionnel",
        ),
        migrations.RemoveField(
            model_name="financement",
            name="est_appui_budgetaire",
        ),
        migrations.RemoveField(
            model_name="financement",
            name="taux_conversion_contractuel",
        ),
        migrations.AddField(
            model_name="decaissement",
            name="date_prevue",
            field=models.DateField(
                blank=True,
                help_text="Date planifiée du décaissement (suivi du pipeline)",
                null=True,
                verbose_name="Date prévisionnelle",
            ),
        ),
        migrations.AlterField(
            model_name="decaissement",
            name="date_decaissement",
            field=models.DateField(verbose_name="Date effective de décaissement"),
        ),
    ]
