# Generated by Django 5.2.11 on 2026-05-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financements", "0003_remove_decaissement_date_previsionnel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="financement",
            name="montant_circuit_validation",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Montant engagé (validé ou en cours de validation) non encore décaissé",
                max_digits=15,
                verbose_name="Montant en circuit de validation",
            ),
        ),
        migrations.AlterField(
            model_name="financement",
            name="montant_engage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Montant total inscrit dans l'accord de financement",
                max_digits=15,
                verbose_name="Montant du financement (accord)",
            ),
        ),
    ]
