# Generated by Django 5.2.11 on 2026-03-13 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bailleurs", "0002_bailleur_categorie_institutionnelle"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("superadmin", "Super Administrateur"),
                            ("directeur", "Directeur / Haute fonction"),
                            ("point_focal", "Point Focal Bailleur"),
                            ("lecteur", "Lecteur (consultation seule)"),
                        ],
                        default="point_focal",
                        max_length=20,
                        verbose_name="Rôle",
                    ),
                ),
                (
                    "fonction",
                    models.CharField(
                        choices=[
                            ("ministre", "Ministre"),
                            ("dircab", "Directeur de Cabinet"),
                            ("dca", "Directeur de la Coopération et de l'Aide"),
                            ("conseiller", "Conseiller Technique"),
                            ("chef_service", "Chef de Service"),
                            ("charge_suivi", "Chargé de Suivi"),
                            ("point_focal", "Point Focal Bailleur"),
                            ("autre", "Autre"),
                        ],
                        default="point_focal",
                        max_length=30,
                        verbose_name="Fonction",
                    ),
                ),
                (
                    "titre_poste",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Titre du poste"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Téléphone"
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Compte approuvé"),
                ),
                (
                    "date_demande",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'inscription"
                    ),
                ),
                (
                    "date_approbation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'approbation"
                    ),
                ),
                (
                    "notes_admin",
                    models.TextField(blank=True, verbose_name="Notes administrateur"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_users",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approuvé par",
                    ),
                ),
                (
                    "bailleurs",
                    models.ManyToManyField(
                        blank=True,
                        related_name="points_focaux",
                        to="bailleurs.bailleur",
                        verbose_name="Bailleurs (Point focal)",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil utilisateur",
                "verbose_name_plural": "Profils utilisateurs",
                "ordering": ["-date_demande"],
            },
        ),
    ]
