# Generated by Django 5.2.11 on 2026-05-02 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="fonction",
            field=models.CharField(
                choices=[
                    ("ministre", "Ministre"),
                    ("dircab", "Directeur de Cabinet"),
                    ("dircab_adjoint", "Directeur de Cabinet Adjoint"),
                    ("chef_cabinet", "Chef de Cabinet"),
                    ("conseiller", "Conseiller Technique"),
                    ("dg", "Directeur Général"),
                    ("charge_etudes", "Chargé d'Etudes"),
                    ("point_focal", "Point Focal Bailleur"),
                    ("autre", "Autre"),
                ],
                default="point_focal",
                max_length=30,
                verbose_name="Fonction",
            ),
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Création"),
                            ("update", "Modification"),
                            ("delete", "Suppression"),
                            ("approve", "Approbation"),
                            ("login", "Connexion"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model_name", models.CharField(max_length=50, verbose_name="Objet")),
                (
                    "object_repr",
                    models.CharField(max_length=200, verbose_name="Description"),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("details", models.TextField(blank=True, verbose_name="Détails")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal d'activité",
                "verbose_name_plural": "Journal d'activité",
                "ordering": ["-timestamp"],
            },
        ),
    ]
