# Generated by Django 5.2.11 on 2026-05-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_activity_log_new_fonctions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="fonction",
            field=models.CharField(
                choices=[
                    ("ministre", "Ministre"),
                    ("dircab", "Directeur de Cabinet"),
                    ("dircab_adjoint", "Directeur de Cabinet Adjoint"),
                    ("chef_cabinet", "Chef de Cabinet"),
                    ("conseiller", "Conseiller Technique"),
                    ("dg", "Directeur Général"),
                    ("charge_etudes", "Chargé d'Etudes"),
                    ("point_focal", "Point Focal"),
                    ("autre", "Autre"),
                ],
                default="point_focal",
                max_length=30,
                verbose_name="Fonction",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Super Administrateur"),
                    ("directeur", "Directeur / Haute fonction"),
                    ("point_focal", "Point Focal"),
                    ("lecteur", "Lecteur (consultation seule)"),
                ],
                default="point_focal",
                max_length=20,
                verbose_name="Rôle",
            ),
        ),
    ]
