# Generated by Django 5.2.11 on 2026-05-18 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "projets",
            "0004_programme_regiongeographique_projet_categorie_retard_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alerte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_alerte",
                    models.CharField(
                        choices=[
                            ("retard_avere", "Retard avéré"),
                            ("faible_decaissement", "Faible taux de décaissement"),
                            ("discordance", "Discordance physique/financier"),
                            ("inactivite", "Données non mises à jour"),
                            ("signalement_manuel", "Signalement manuel"),
                        ],
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                (
                    "niveau",
                    models.CharField(
                        choices=[
                            ("critique", "Critique"),
                            ("attention", "Attention"),
                            ("information", "Information"),
                        ],
                        default="attention",
                        max_length=20,
                        verbose_name="Niveau",
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
                ("details", models.TextField(blank=True, verbose_name="Détails")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("traitee", "Traitée"),
                            ("ignoree", "Ignorée"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_traitement", models.DateTimeField(blank=True, null=True)),
                (
                    "note_traitement",
                    models.TextField(blank=True, verbose_name="Note de traitement"),
                ),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertes",
                        to="projets.projet",
                        verbose_name="Projet concerné",
                    ),
                ),
                (
                    "signale_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alertes_signalees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Signalé par",
                    ),
                ),
                (
                    "traite_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alertes_traitees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Traité par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerte",
                "verbose_name_plural": "Alertes",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="ParametreSysteme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cle",
                    models.CharField(
                        choices=[
                            (
                                "seuil_faible_decaissement",
                                "Seuil taux de décaissement faible (%)",
                            ),
                            (
                                "seuil_discordance",
                                "Seuil discordance physique/financier (points)",
                            ),
                            (
                                "seuil_inactivite_jours",
                                "Délai d'inactivité avant alerte (jours)",
                            ),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Paramètre",
                    ),
                ),
                ("valeur", models.CharField(max_length=50, verbose_name="Valeur")),
                ("description", models.TextField(blank=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètre système",
                "verbose_name_plural": "Paramètres système",
            },
        ),
    ]
