# Generated by Django 5.2.11 on 2026-02-24 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlanNational",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255, verbose_name="Nom du plan")),
                (
                    "sigle",
                    models.CharField(blank=True, max_length=50, verbose_name="Sigle"),
                ),
                (
                    "annee_debut",
                    models.PositiveIntegerField(verbose_name="Année de début"),
                ),
                ("annee_fin", models.PositiveIntegerField(verbose_name="Année de fin")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Plan actif")),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Plan National de Développement",
                "verbose_name_plural": "Plans Nationaux de Développement",
                "ordering": ["-annee_debut"],
            },
        ),
        migrations.CreateModel(
            name="Pilier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField(verbose_name="Numéro")),
                (
                    "nom",
                    models.CharField(max_length=255, verbose_name="Intitulé du pilier"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="piliers",
                        to="pnd.plannational",
                        verbose_name="Plan National",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pilier",
                "verbose_name_plural": "Piliers",
                "ordering": ["plan", "numero"],
                "unique_together": {("plan", "numero")},
            },
        ),
        migrations.CreateModel(
            name="SousObjectif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=20, verbose_name="Numéro")),
                ("nom", models.CharField(max_length=500, verbose_name="Intitulé")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "pilier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sous_objectifs",
                        to="pnd.pilier",
                        verbose_name="Pilier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sous-objectif",
                "verbose_name_plural": "Sous-objectifs",
                "ordering": ["pilier", "numero"],
            },
        ),
    ]
