# Generated by Django 5.2.11 on 2026-02-24 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bailleurs", "0001_initial"),
        ("pnd", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Secteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=255, verbose_name="Nom du secteur"),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=20, verbose_name="Code"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "couleur",
                    models.CharField(
                        default="#3B82F6", max_length=7, verbose_name="Couleur (hex)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Secteur",
                "verbose_name_plural": "Secteurs",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Projet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Code du projet"
                    ),
                ),
                (
                    "titre",
                    models.CharField(max_length=500, verbose_name="Titre du projet"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "montant_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Montant total (USD)",
                    ),
                ),
                (
                    "date_signature",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de signature"
                    ),
                ),
                (
                    "date_debut",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de début"
                    ),
                ),
                (
                    "date_fin_prevue",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de fin prévue"
                    ),
                ),
                (
                    "date_fin_effective",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de fin effective"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("identification", "Identification"),
                            ("preparation", "Préparation"),
                            ("negociation", "Négociation"),
                            ("en_cours", "En cours d'exécution"),
                            ("suspendu", "Suspendu"),
                            ("cloture", "Clôturé"),
                            ("annule", "Annulé"),
                        ],
                        default="identification",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "taux_avancement",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Taux d'avancement physique (%)",
                    ),
                ),
                (
                    "zone_geographique",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Zone géographique"
                    ),
                ),
                (
                    "responsable",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Responsable / Chef de projet",
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "bailleur_principal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bailleurs.bailleur",
                        verbose_name="Bailleur principal",
                    ),
                ),
                (
                    "objectifs_pnd",
                    models.ManyToManyField(
                        blank=True,
                        related_name="projets",
                        to="pnd.sousobjectif",
                        verbose_name="Objectifs PND",
                    ),
                ),
                (
                    "secteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projets.secteur",
                        verbose_name="Secteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projet",
                "verbose_name_plural": "Projets",
                "ordering": ["-date_creation"],
            },
        ),
    ]
