# Generated by Django 5.2.11 on 2026-02-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="devise",
            field=models.CharField(
                choices=[
                    ("USD", "Dollar US (USD)"),
                    ("EUR", "Euro (EUR)"),
                    ("XOF", "Franc CFA (XOF)"),
                    ("GBP", "Livre Sterling (GBP)"),
                    ("JPY", "Yen Japonais (JPY)"),
                    ("CHF", "Franc Suisse (CHF)"),
                    ("CNY", "Yuan Chinois (CNY)"),
                ],
                default="USD",
                max_length=3,
                verbose_name="Devise",
            ),
        ),
        migrations.AlterField(
            model_name="projet",
            name="montant_total",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="Montant total"
            ),
        ),
    ]
