# Generated by Django 5.2.11 on 2026-05-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projets", "0002_projet_devise_alter_projet_montant_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="motif_retard",
            field=models.TextField(
                blank=True,
                help_text="Explication du retard (causes administratives, financières, techniques, etc.)",
                verbose_name="Motif du retard",
            ),
        ),
        migrations.AddField(
            model_name="projet",
            name="responsable_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Email du responsable"
            ),
        ),
        migrations.AddField(
            model_name="projet",
            name="responsable_telephone",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Téléphone du responsable"
            ),
        ),
        migrations.AddField(
            model_name="projet",
            name="structure_responsable",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Structure responsable"
            ),
        ),
    ]
