# Generated by Django 5.2.11 on 2026-05-18 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projets", "0003_add_responsable_enrichis_motif_retard"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Programme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Code"),
                ),
                (
                    "nom",
                    models.CharField(max_length=500, verbose_name="Nom du programme"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "date_debut",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de début"
                    ),
                ),
                (
                    "date_fin",
                    models.DateField(blank=True, null=True, verbose_name="Date de fin"),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Programme",
                "verbose_name_plural": "Programmes",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="RegionGeographique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom de la région"
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=20, verbose_name="Code"),
                ),
            ],
            options={
                "verbose_name": "Région géographique",
                "verbose_name_plural": "Régions géographiques",
                "ordering": ["nom"],
            },
        ),
        migrations.AddField(
            model_name="projet",
            name="categorie_retard",
            field=models.CharField(
                blank=True,
                choices=[
                    ("administratif", "Administratif"),
                    ("financier", "Financier"),
                    ("technique", "Technique"),
                    ("contextuel", "Contextuel"),
                    ("autre", "Autre"),
                ],
                max_length=20,
                verbose_name="Catégorie du retard",
            ),
        ),
        migrations.AddField(
            model_name="projet",
            name="contrepartie_etat",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                verbose_name="Part de l'État (contrepartie nationale)",
            ),
        ),
        migrations.AddField(
            model_name="projet",
            name="niveau_intervention",
            field=models.CharField(
                blank=True,
                choices=[
                    ("national", "National"),
                    ("regional", "Régional"),
                    ("local", "Local"),
                ],
                max_length=20,
                verbose_name="Niveau d'intervention",
            ),
        ),
        migrations.AddField(
            model_name="projet",
            name="responsables_locaux",
            field=models.TextField(
                blank=True,
                help_text="Noms des responsables locaux (un par ligne)",
                verbose_name="Responsables locaux",
            ),
        ),
        migrations.AddField(
            model_name="projet",
            name="taux_avancement_financier",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Taux d'avancement financier (%)",
            ),
        ),
        migrations.AddField(
            model_name="projet",
            name="type_cooperation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("investissement", "Projet d'investissement"),
                    ("appui_budgetaire", "Appui budgétaire"),
                    ("assistance_technique", "Assistance technique"),
                    ("subvention_programme", "Subvention programme"),
                    ("autre", "Autre"),
                ],
                max_length=30,
                verbose_name="Type de coopération",
            ),
        ),
        migrations.CreateModel(
            name="PieceJointe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_document",
                    models.CharField(
                        choices=[
                            ("accord", "Accord de financement"),
                            ("rapport", "Rapport d'avancement"),
                            ("pv", "PV de réunion"),
                            ("audit", "Rapport d'audit"),
                            ("autre", "Autre document"),
                        ],
                        default="autre",
                        max_length=20,
                        verbose_name="Type de document",
                    ),
                ),
                (
                    "titre",
                    models.CharField(max_length=255, verbose_name="Titre du document"),
                ),
                (
                    "fichier",
                    models.FileField(
                        upload_to="pieces_jointes/%Y/%m/", verbose_name="Fichier"
                    ),
                ),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
                (
                    "ajoute_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ajouté par",
                    ),
                ),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pieces_jointes",
                        to="projets.projet",
                        verbose_name="Projet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pièce jointe",
                "verbose_name_plural": "Pièces jointes",
                "ordering": ["-date_ajout"],
            },
        ),
        migrations.AddField(
            model_name="projet",
            name="programme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projets.programme",
                verbose_name="Programme de rattachement",
            ),
        ),
        migrations.AddField(
            model_name="projet",
            name="zones",
            field=models.ManyToManyField(
                blank=True,
                related_name="projets",
                to="projets.regiongeographique",
                verbose_name="Zones géographiques d'intervention",
            ),
        ),
        migrations.CreateModel(
            name="StatutHistorique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ancien_statut",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Ancien statut"
                    ),
                ),
                (
                    "nouveau_statut",
                    models.CharField(max_length=20, verbose_name="Nouveau statut"),
                ),
                (
                    "date_changement",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date du changement"
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, verbose_name="Commentaire"),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique_statuts",
                        to="projets.projet",
                        verbose_name="Projet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique de statut",
                "verbose_name_plural": "Historiques de statut",
                "ordering": ["-date_changement"],
            },
        ),
    ]
