# Generated by Django 5.2.11 on 2026-05-25 01:47

import django.db.models.deletion
import django.utils.timezone
import projets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projets",
            "0004_programme_regiongeographique_projet_categorie_retard_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projet",
            name="zones",
        ),
        migrations.RemoveField(
            model_name="statuthistorique",
            name="modifie_par",
        ),
        migrations.RemoveField(
            model_name="statuthistorique",
            name="projet",
        ),
        migrations.AlterModelOptions(
            name="piecejointe",
            options={
                "ordering": ["-date_upload"],
                "verbose_name": "Pièce jointe",
                "verbose_name_plural": "Pièces jointes",
            },
        ),
        migrations.RemoveField(
            model_name="piecejointe",
            name="ajoute_par",
        ),
        migrations.RemoveField(
            model_name="piecejointe",
            name="date_ajout",
        ),
        migrations.RemoveField(
            model_name="projet",
            name="categorie_retard",
        ),
        migrations.RemoveField(
            model_name="projet",
            name="contrepartie_etat",
        ),
        migrations.RemoveField(
            model_name="projet",
            name="responsables_locaux",
        ),
        migrations.RemoveField(
            model_name="projet",
            name="type_cooperation",
        ),
        migrations.AddField(
            model_name="piecejointe",
            name="date_upload",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date d'ajout",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="piecejointe",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="piecejointe",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Déposé par",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="objectif_strategique",
            field=models.TextField(blank=True, verbose_name="Objectif stratégique"),
        ),
        migrations.AddField(
            model_name="programme",
            name="secteur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projets.secteur",
                verbose_name="Secteur principal",
            ),
        ),
        migrations.AddField(
            model_name="projet",
            name="motif_retard_categorie",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Non concerné"),
                    ("administratif", "Administratif"),
                    ("financier", "Financier"),
                    ("technique", "Technique"),
                    ("contextuel", "Contextuel (sécurité, climat...)"),
                    ("autre", "Autre"),
                ],
                default="",
                help_text="Obligatoire si le projet est en retard",
                max_length=20,
                verbose_name="Catégorie du motif de retard",
            ),
        ),
        migrations.AddField(
            model_name="projet",
            name="part_etat",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Montant de la contrepartie nationale dans la devise du projet",
                max_digits=15,
                verbose_name="Part de l'État (contrepartie)",
            ),
        ),
        migrations.AlterField(
            model_name="piecejointe",
            name="fichier",
            field=models.FileField(
                upload_to=projets.models.piece_jointe_upload_to, verbose_name="Fichier"
            ),
        ),
        migrations.AlterField(
            model_name="piecejointe",
            name="type_document",
            field=models.CharField(
                choices=[
                    ("accord", "Accord de financement"),
                    ("rapport", "Rapport d'avancement"),
                    ("pv", "Procès-verbal de réunion"),
                    ("audit", "Rapport d'audit"),
                    ("autre", "Autre document"),
                ],
                default="autre",
                max_length=20,
                verbose_name="Type de document",
            ),
        ),
        migrations.AlterField(
            model_name="programme",
            name="code",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Code du programme"
            ),
        ),
        migrations.AlterField(
            model_name="programme",
            name="date_fin",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de fin prévue"
            ),
        ),
        migrations.AlterField(
            model_name="projet",
            name="motif_retard",
            field=models.TextField(
                blank=True,
                help_text="Explication détaillée du retard",
                verbose_name="Détail du motif de retard",
            ),
        ),
        migrations.AlterField(
            model_name="projet",
            name="niveau_intervention",
            field=models.CharField(
                blank=True,
                choices=[
                    ("national", "National"),
                    ("regional", "Régional"),
                    ("local", "Local"),
                ],
                default="",
                max_length=20,
                verbose_name="Niveau d'intervention",
            ),
        ),
        migrations.AlterField(
            model_name="projet",
            name="programme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projets",
                to="projets.programme",
                verbose_name="Programme de rattachement",
            ),
        ),
        migrations.AlterField(
            model_name="projet",
            name="taux_avancement_financier",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Pourcentage d'exécution financière (peut différer du taux de décaissement)",
                max_digits=5,
                verbose_name="Taux d'avancement financier (%)",
            ),
        ),
        migrations.CreateModel(
            name="ResponsableLocal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255, verbose_name="Nom et prénom")),
                (
                    "fonction",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Fonction"
                    ),
                ),
                (
                    "structure",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Structure / Localité"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Région d'intervention"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsables_locaux",
                        to="projets.projet",
                        verbose_name="Projet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Responsable local",
                "verbose_name_plural": "Responsables locaux",
                "ordering": ["nom"],
            },
        ),
        migrations.DeleteModel(
            name="RegionGeographique",
        ),
        migrations.DeleteModel(
            name="StatutHistorique",
        ),
    ]
