# Generated by Django 5.2.11 on 2026-05-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projets", "0005_remove_projet_zones_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="date_1er_decaissement_effectif",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date effective du 1er décaissement"
            ),
        ),
        migrations.AddField(
            model_name="projet",
            name="date_1er_decaissement_prevu",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date prévue du 1er décaissement"
            ),
        ),
        migrations.AddField(
            model_name="projet",
            name="part_etat_pourcentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Pourcentage de la contrepartie nationale sur le montant total du projet",
                max_digits=5,
                verbose_name="Part de l'État (%)",
            ),
        ),
        migrations.AlterField(
            model_name="projet",
            name="montant_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Montant total prévu d'après l'accord de financement (budget total du projet)",
                max_digits=15,
                verbose_name="Montant total du projet (accord de financement)",
            ),
        ),
        migrations.AlterField(
            model_name="projet",
            name="part_etat",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Montant de la contrepartie nationale dans la devise du projet (calculé auto si % renseigné)",
                max_digits=15,
                verbose_name="Part de l'État — montant (contrepartie)",
            ),
        ),
    ]
