# Generated by Django 5.2.11 on 2026-05-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projets", "0006_projet_date_1er_decaissement_effectif_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projet",
            name="devise",
            field=models.CharField(
                choices=[
                    ("USD", "Dollar US (USD)"),
                    ("EUR", "Euro (EUR)"),
                    ("XOF", "Franc CFA (XOF)"),
                    ("UC", "Unité de Compte BAD (UC)"),
                    ("GBP", "Livre Sterling (GBP)"),
                    ("JPY", "Yen Japonais (JPY)"),
                    ("CHF", "Franc Suisse (CHF)"),
                    ("CNY", "Yuan Chinois (CNY)"),
                ],
                default="USD",
                max_length=3,
                verbose_name="Devise",
            ),
        ),
    ]
