# Generated by Django 5.2.11 on 2026-05-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projets", "0007_alter_projet_devise_uc"),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="taux_decaissement_prevu_annee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Objectif de décaissement pour l'année en cours, en % du montant total du projet",
                max_digits=5,
                verbose_name="Taux de décaissement prévu pour l'année (%)",
            ),
        ),
    ]
