# Generated by Django 5.2.11 on 2026-05-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projets", "0008_add_circuit_validation_and_taux_prevu_annee"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="responsable",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Responsable / Chef de programme",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="statut",
            field=models.CharField(
                blank=True,
                choices=[
                    ("identification", "Identification"),
                    ("preparation", "Préparation"),
                    ("negociation", "Négociation"),
                    ("en_cours", "En cours d'exécution"),
                    ("suspendu", "Suspendu"),
                    ("cloture", "Clôturé"),
                    ("annule", "Annulé"),
                ],
                default="identification",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="structure_responsable",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Structure responsable"
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="taux_avancement",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Taux d'avancement physique (%)",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="zone_geographique",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Zone géographique"
            ),
        ),
    ]
