# Generated by Django 5.2.11 on 2026-05-29 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bailleurs",
            "0004_alter_bailleur_contact_telephone_alter_bailleur_logo_and_more",
        ),
        ("projets", "0009_programme_extra_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="bailleur_principal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bailleurs.bailleur",
                verbose_name="Bailleur principal",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="date_fin_effective",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de fin effective"
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="date_signature",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de signature"
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="devise",
            field=models.CharField(
                choices=[
                    ("USD", "Dollar US (USD)"),
                    ("EUR", "Euro (EUR)"),
                    ("XOF", "Franc CFA (XOF)"),
                    ("UC", "Unité de Compte BAD (UC)"),
                    ("GBP", "Livre Sterling (GBP)"),
                    ("JPY", "Yen Japonais (JPY)"),
                    ("CHF", "Franc Suisse (CHF)"),
                    ("CNY", "Yuan Chinois (CNY)"),
                ],
                default="USD",
                max_length=3,
                verbose_name="Devise",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="montant_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                verbose_name="Montant total du programme",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="taux_avancement_financier",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Taux d'avancement financier (%)",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="taux_decaissement_prevu_annee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Taux de décaissement prévu annuel (%)",
            ),
        ),
    ]
