# Generated by Django 5.2.11 on 2026-06-02 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projets", "0010_programme_financial_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="programme",
            name="taux_avancement",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Taux d'exécution physique (%)",
            ),
        ),
        migrations.AlterField(
            model_name="projet",
            name="taux_avancement",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Taux d'exécution physique (%)",
            ),
        ),
        migrations.CreateModel(
            name="CommentaireProjet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_commentaire",
                    models.CharField(
                        choices=[
                            ("retard", "Justification de retard"),
                            ("attention", "Point d'attention"),
                            ("blocage", "Point de blocage"),
                            ("observation", "Observation générale"),
                        ],
                        default="observation",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "niveau",
                    models.CharField(
                        choices=[
                            ("critique", "Critique"),
                            ("important", "Important"),
                            ("information", "Information"),
                        ],
                        default="information",
                        max_length=20,
                        verbose_name="Niveau",
                    ),
                ),
                ("contenu", models.TextField(verbose_name="Contenu")),
                (
                    "date_commentaire",
                    models.DateField(blank=True, null=True, verbose_name="Date"),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        default="manuel",
                        help_text="'manuel', 'import_excel', etc.",
                        max_length=100,
                        verbose_name="Source",
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "auteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur",
                    ),
                ),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commentaires",
                        to="projets.projet",
                        verbose_name="Projet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commentaire projet",
                "verbose_name_plural": "Commentaires projets",
                "ordering": ["-date_commentaire", "-date_creation"],
            },
        ),
    ]
