# Generated by Django 5.2.11 on 2026-06-03 03:13

from django.db import migrations

SECTEURS = [
    ('Agriculture/Développement rural', 'AGR'),
    ('Développement Urbain',            'DEV_URB'),
    ('Eau & Assainissement',            'EAU'),
    ('Environnement & Climat',          'ENV'),
    ('Gouvernance',                     'GOV'),
    ('Infrastructure & Transport',      'INFRA'),
    ('Protection Sociale',              'PROT_SOC'),
    ('Santé',                           'SANTE'),
    ('Éducation/Formation',             'EDU'),
    ('Énergie',                         'ENERGIE'),
    ('Logement',                        'LOGEMENT'),
    ('Finance Publique',                'FIN_PUB'),
    ('Autre',                           'AUTRE'),
]


def create_secteurs(apps, schema_editor):
    Secteur = apps.get_model('projets', 'Secteur')
    for nom, code in SECTEURS:
        Secteur.objects.get_or_create(nom=nom, defaults={'code': code})


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("projets", "0011_commentaire_projet"),
    ]

    operations = [
        migrations.RunPython(create_secteurs, noop),
    ]
