# Generated by Django 5.2.11 on 2026-06-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projets", "0012_populate_secteurs_ci"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="part_etat",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Montant de la contrepartie nationale (État CI) en FCFA",
                max_digits=15,
                null=True,
                verbose_name="Part État (montant XOF)",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="part_etat_pourcentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Pourcentage de la contrepartie nationale sur le montant total",
                max_digits=5,
                null=True,
                verbose_name="Part État (%)",
            ),
        ),
        migrations.AlterField(
            model_name="programme",
            name="statut",
            field=models.CharField(
                blank=True,
                choices=[
                    ("identification", "Identification"),
                    ("preparation", "Préparation"),
                    ("negociation", "Négociation"),
                    ("non_demarre", "Approuvé mais non démarré"),
                    ("en_cours", "En cours d'exécution"),
                    ("en_instance_cloture", "En instance de clôture"),
                    ("suspendu", "Suspendu"),
                    ("cloture", "Clôturé"),
                    ("annule", "Annulé"),
                ],
                default="identification",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="projet",
            name="statut",
            field=models.CharField(
                choices=[
                    ("identification", "Identification"),
                    ("preparation", "Préparation"),
                    ("negociation", "Négociation"),
                    ("non_demarre", "Approuvé mais non démarré"),
                    ("en_cours", "En cours d'exécution"),
                    ("en_instance_cloture", "En instance de clôture"),
                    ("suspendu", "Suspendu"),
                    ("cloture", "Clôturé"),
                    ("annule", "Annulé"),
                ],
                default="identification",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
